import './globals.css'
import { Anonymous_Pro } from 'next/font/google'

const anonymousPro = Anonymous_Pro({ subsets: ['cyrillic', 'latin'], weight: ['700'] })

export const metadata = {
  title: 'Среда | Медиа с улиц Ханты-Мансийска',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={anonymousPro.className}>{children}</body>
    </html>
  )
}
